vim.cmd("set background=dark")
vim.cmd("let g:everforest_disable_italic_comment = 1")
vim.cmd("let g:everforest_background = 'hard'")
-- vim.cmd("let g:everforest_better_performance = 1")
vim.cmd('colorscheme everforest')
