#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/personal/ ~/work/ -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)
PP_EXPORT='export PYTHONPATH=$(git rev-parse --show-toplevel)'

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -ds $selected_name -c $selected
    echo "setting python path"
    tmux setenv -t $selected_name PYTHONPATH "$selected:$PYTHONPATH"
    tmux a -t $selected_name
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
    echo "setting python path"
    tmux setenv -t $selected_name PYTHONPATH "$selected:$PYTHONPATH"
fi

tmux switch-client -Et $selected_name
