# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: [push]
  # Triggers the workflow on push or pull request events but only for the "master" branch
    # # this should make these jobs run on all branches
    # # branches: [ "master" ]
  # pull_request:
    # branches: [ "master" ]
  # # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  python-question-tests:
    runs-on: ubuntu-latest
    container: 
      image: python:3.10
      env:
        PYTHONPATH: $GITHUB_WORKSPACE
    steps:
      - uses: actions/checkout@v3
      - name: day-one-test
        run: |
          pwd
          ls
          echo $PYTHONPATH
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          python3 python/day1/test/test_question_1.py

